### ISSUE TITLE
A doubt

### ISSUE THREAD

**Issue by CadisRaziel** [david-legend/david-legend.github.io#2]
I really liked your site and I saw that you are not using any kind of 'SEO', could you tell me where you hosted this site and how did you make the 'SEO' so good that your site appears first in the Google ?

sorry for the question but I really liked what you did and I really want to learn how to do it too.

Thanks.

**Comment by david-legend** [comment]
I am hosting it on firebase. I didn't do much but I think the domain name is in my bio on popular platforms like LinkedIn, Github, Twitter & Instagram. Not sure if that affected the SEO. But if multiple sites are pointing to it, Google can rank it high.

**Comment by CadisRaziel** [comment]
@david-legend thank you very much, i will search this in firebase thank you very much

**Comment by david-legend** [comment]
Welcome
